### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by saltsoftdrink** [Tech5G5G/Fluentver#3]
This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)

**Comment by Tech5G5G** [comment]
The packages don't work for some reason. Use the MS Store or winget

**Comment by saltsoftdrink** [comment]
> The packages don't work for some reason. Use the MS Store or winget

Why don't you try to fix it?
